name: Get Next Version Action

description: GitHub Actions to get next version from commit histories.

author: technote-space

outputs:
  version:
    description: next version

branding:
  icon: 'info'
  color: 'green'

runs:
  using: node12
  main: lib/main.js
